user_name: "Konstantin Kostadinov"
user_email: "kostadinov92@gmail.com"
timezone: "Europe/Sofia"
locale: "en_US.UTF-8"
default_editor: "nvim"
default_branch: "main"
keyboard_layouts: "us,bg"
keyboard_variant: ",phonetic"
keyboard_toggle: "grp:alt_shift_toggle"
