- name: Create kitty config directory
  become: false
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/kitty"
    state: directory
    mode: "0755"

- name: Copy kitty config
  become: false
  ansible.builtin.copy:
    src: kitty.conf
    dest: "{{ lookup('env', 'HOME') }}/.config/kitty/kitty.conf"
    mode: "0644"

- name: Copy zshrc
  become: false
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    mode: "0644"
