#!/bin/bash
# Click to open file manager at /
case $BLOCK_BUTTON in
    1) nemo / & ;;
esac

ROOT=$(df -h / | awk 'NR==2{print $3 "/" $2}')
HOME_DISK=$(df -h /home | awk 'NR==2{print $3 "/" $2}')
USE_PCT=$(df / | awk 'NR==2{gsub(/%/,""); print $5}')

ICON=$'\uf0a0'
echo "$ICON / $ROOT   /home $HOME_DISK"
echo "$ICON / $ROOT"

if [ "$USE_PCT" -ge 90 ]; then
    echo "#BF616A"
elif [ "$USE_PCT" -ge 75 ]; then
    echo "#EBCB8B"
fi
