#!/bin/bash
# Click to open network settings
case $BLOCK_BUTTON in
    1) nm-connection-editor & ;;
    3) nmcli device wifi rescan 2>/dev/null & ;;
esac

WIFI=$(nmcli -t -f active,ssid dev wifi 2>/dev/null | grep '^yes' | cut -d: -f2)
ETH=$(nmcli -t -f type,state dev 2>/dev/null | grep 'ethernet:connected')

ICON_WIFI=$'\uf1eb'
ICON_ETH=$'\uf796'
ICON_OFF=$'\uf127'

if [ -n "$WIFI" ]; then
    echo "$ICON_WIFI $WIFI"
    echo "$ICON_WIFI $WIFI"
elif [ -n "$ETH" ]; then
    echo "$ICON_ETH ethernet"
    echo "$ICON_ETH eth"
else
    echo "$ICON_OFF disconnected"
    echo "$ICON_OFF disc"
    echo "#BF616A"
fi
