- name: Set timezone
  community.general.timezone:
    name: Europe/Sofia

- name: Set locale
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set default locale
  ansible.builtin.copy:
    dest: /etc/default/locale
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
    mode: "0644"

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Enable unattended-upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    mode: "0644"
