- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set locale
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present

- name: Set default locale
  ansible.builtin.copy:
    dest: /etc/default/locale
    content: |
      LANG={{ locale }}
      LC_ALL={{ locale }}
    mode: "0644"

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Enable unattended-upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    mode: "0644"
