- name: Configure git user name
  become: false
  community.general.git_config:
    name: user.name
    value: "Konstantin Kostadinov"
    scope: global

- name: Configure git user email
  become: false
  community.general.git_config:
    name: user.email
    value: "kostadinov92@gmail.com"
    scope: global

- name: Set default branch to main
  become: false
  community.general.git_config:
    name: init.defaultBranch
    value: main
    scope: global

- name: Set default editor to nvim
  become: false
  community.general.git_config:
    name: core.editor
    value: nvim
    scope: global
