- name: Configure git user name
  become: false
  community.general.git_config:
    name: user.name
    value: "{{ user_name }}"
    scope: global

- name: Configure git user email
  become: false
  community.general.git_config:
    name: user.email
    value: "{{ user_email }}"
    scope: global

- name: Set default branch to main
  become: false
  community.general.git_config:
    name: init.defaultBranch
    value: "{{ default_branch }}"
    scope: global

- name: Set default editor to nvim
  become: false
  community.general.git_config:
    name: core.editor
    value: "{{ default_editor }}"
    scope: global
