- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /usr/share/keyrings/kubernetes.asc
    mode: "0644"

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    filename: kubernetes
    state: present

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: true
